
import { documentContents } from './document-content';

interface DLDDocument {
  id: number;
  name: string;
  group: string;
  lang: 'en' | 'ar';
  summary: string;
  keyTopics: string[];
  content: string;
}

export const dldChainDocuments: DLDDocument[] = [
  {
    id: 1,
    name: "DLDCHAIN Project Vision",
    group: 'vision',
    lang: 'en',
    summary: "A high-level overview of the DLDCHAIN project, its goals, and its potential impact on Dubai's real estate market.",
    keyTopics: ["Sovereign Ledger", "Tokenization", "Smart Contracts", "Ecosystem"],
    content: documentContents['vision-en']
  },
  {
    id: 19,
    name: "رؤية مشروع DLDCHAIN",
    group: 'vision',
    lang: 'ar',
    summary: "نظرة عامة عالية المستوى على مشروع DLDCHAIN وأهدافه وتأثيره المحتمل على سوق العقارات في دبي.",
    keyTopics: ["السجل السيادي", "الترميز", "العقود الذكية", "النظام البيئي"],
    content: documentContents['vision-ar']
  },
  {
    id: 2,
    name: "1.1: From Registry to Operating System",
    group: 'part-1',
    lang: 'en',
    summary: 'Explains the evolution of real estate management from a simple registry to a dynamic, programmable operating system under sovereign authority.',
    keyTopics: ['Programmable Asset', 'City as Code', 'Sovereign Digital ID'],
    content: documentContents['article-1-1'],
  },
  {
    id: 3,
    name: '1.2: DLD as Chain Governor',
    group: 'part-1',
    lang: 'en',
    summary: 'Defines the Dubai Land Department’s central role as the ultimate authority and sovereign operator of the DLDCHAIN network.',
    keyTopics: ['Sovereign Anchor', 'Authoritative Node', 'Bespoke Design'],
    content: documentContents['article-1-2'],
  },
  {
    id: 4,
    name: '1.3: Cross-Entity Integration',
    group: 'part-1',
    lang: 'en',
    summary: 'Details the secure interconnections with other government entities to create a unified real estate ecosystem, eliminating legacy data silos.',
    keyTopics: ['GDRFA', 'CBUAE', 'Ministry of Justice', 'Legacy Silos'],
    content: documentContents['article-1-3'],
  },
  {
    id: 5,
    name: '2.1: DLD-AED Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Introduces the DLD Digital Dirham (DLD-AED) as the native, fiat-pegged stablecoin for all transactions within the ecosystem.',
    keyTopics: ['Stablecoin', 'Fiat-Only', 'Exclusive Currency'],
    content: documentContents['article-2-1'],
  },
  {
    id: 6,
    name: '2.2: DLD-AED Mechanism',
    group: 'part-2',
    lang: 'en',
    summary: 'Explains the conversion mechanism, collateralization, and the strategic importance of the fiat-only approach for investor confidence.',
    keyTopics: ['Collateralization', 'KYC Tiers', 'Volatility Mitigation'],
    content: documentContents['article-2-2'],
  },
  {
    id: 7,
    name: '2.3: EBRAM Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Presents EBRAM as a legal-transactional, domain-specific language designed to automate real estate law and agreements.',
    keyTopics: ['Legal Language', 'Domain-Specific', 'Dual Language'],
    content: documentContents['article-2-3'],
  },
  {
    id: 8,
    name: '2.4: EBRAM Syntax & Logic',
    group: 'part-2',
    lang: 'en',
    summary: 'Details the core constructs, operators, and the hierarchical smart contract tree architecture used by EBRAM to structure assets.',
    keyTopics: ['Logic Trees', 'Smart Contract Tree', 'Ownerable Asset'],
    content: documentContents['article-2-4'],
  },
  {
    id: 9,
    name: '2.5: EBRAM Integrations',
    group: 'part-2',
    lang: 'en',
    summary: 'Describes how EBRAM integrates with key systems like Ejari, Milka, and Trakheesi to ensure real-world validity and compliance.',
    keyTopics: ['Ejari Integration', 'Process Flow', 'Legal Enforcement'],
    content: documentContents['article-2-5'],
  },
  {
    id: 10,
    name: '2.6: EBRAM Smart Pricing',
    group: 'part-2',
    lang: 'en',
    summary: 'Explains how EBRAM acts as a dynamic price setter for tokenization, using a complex model based on historical and real-time data.',
    keyTopics: ['Price Setter', 'Dynamic Pricing', 'Market Dynamics'],
    content: documentContents['article-2-6'],
  },
  {
    id: 11,
    name: '2.7: EBRAMGPT Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Introduces EBRAMGPT as the AI-powered legal advisor that acts as the interface between users and the legal logic of DLDCHAIN.',
    keyTopics: ['AI Legal Advisor', 'Natural Language', 'Intelligent Engine'],
    content: documentContents['article-2-7'],
  },
  {
    id: 12,
    name: '2.8: EBRAMGPT Functionalities',
    group: 'part-2',
    lang: 'en',
    summary: 'Details the key functions of EBRAMGPT, including bi-directional language conversion and context-aware contract drafting.',
    keyTopics: ['Language Conversion', 'Context-Aware', 'Unified Access'],
    content: documentContents['article-2-8'],
  },
  {
    id: 13,
    name: '2.9: EBRAMGPT Systems & Impact',
    group: 'part-2',
    lang: 'en',
    summary: 'Outlines how EBRAMGPT connects to other systems for real-time data and its impact, including the EBRAM ML NOTES™ for collective intelligence.',
    keyTopics: ['Real-Time Systems', 'EBRAM ML NOTES™', 'Collective Intelligence'],
    content: documentContents['article-2-9'],
  },
  {
    id: 14,
    name: '2.10: DXBTOKENS Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Presents DXBTOKENS as a new value system based on legally-sanctioned ownership, shifting from rental income to intrinsic asset value.',
    keyTopics: ['Value System', 'Tokenized Ownership', 'Rent is a Pool'],
    content: documentContents['article-2-10'],
  },
  {
    id: 15,
    name: '2.11: DXBTOKENS Lifecycle',
    group: 'part-2',
    lang: 'en',
    summary: 'Details the full lifecycle of a tokenized property, including initiation, the MAKE event, token allocation, and market trading.',
    keyTopics: ['Tokenization Lifecycle', 'MAKE Event', 'AI Market-Making'],
    content: documentContents['article-2-11'],
  },
  {
    id: 16,
    name: '2.12: The MAKE System Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Introduces MAKE as the sovereign liquidity and escrow engine of DLDCHAIN, backing every tokenized asset with 100% AED liquidity.',
    keyTopics: ['Sovereign Liquidity', 'Escrow Backbone', 'Air-Gapped'],
    content: documentContents['article-2-12'],
  },
  {
    id: 17,
    name: '2.13: MAKE System Lifecycle',
    group: 'part-2',
    lang: 'en',
    summary: 'Describes the full cycle of liquidity from tokenization initiation to the MAKE-IN and MAKE-OUT events, and its revenue model.',
    keyTopics: ['MAKE Cycle', 'Liquidity Flow', 'Revenue Model'],
    content: documentContents['article-2-13'],
  },
  {
    id: 18,
    name: '2.14: MAKE System Security',
    group: 'part-2',
    lang: 'en',
    summary: 'Explains the security and governance model of the MAKE system, emphasizing its air-gapped state and lack of DeFi interoperability.',
    keyTopics: ['Air-Gapped', 'Multi-Party Validation', 'Controlled Ecosystem'],
    content: documentContents['article-2-14'],
  },
  {
    id: 20,
    name: '2.15: Mashroi Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Positions Mashroi as the national real estate intelligence grid, an AI-integrated system for performance management and licensing.',
    keyTopics: ['Intelligence Grid', 'Mandatory Gateway', 'Sovereign Interface'],
    content: documentContents['article-2-15'],
  },
  {
    id: 21,
    name: '2.16: Mashroi Functionalities',
    group: 'part-2',
    lang: 'en',
    summary: 'Details the key services Mashroi provides for brokers, including smart licensing, education, visa facilitation, and job matching.',
    keyTopics: ['Smart Licensing', 'CPD', 'Visa Gateway', 'Job Matching'],
    content: documentContents['article-2-16'],
  },
  {
    id: 22,
    name: '2.17: Mashroi Governance',
    group: 'part-2',
    lang: 'en',
    summary: 'Explains Mashroi’s performance-based governance, where opportunity is for the deserving, and its role as a governless intelligence system.',
    keyTopics: ['Performance Governance', 'Governless Enforcement', 'Meritocracy'],
    content: documentContents['article-2-17'],
  },
  {
    id: 23,
    name: '2.18: UNIVESTOR Wallet Overview',
    group: 'part-2',
    lang: 'en',
    summary: 'Introduces the universal wallet as the single, secure interface for all real estate interactions, featuring role-based, tiered access.',
    keyTopics: ['Universal Wallet', 'Tiered Access', 'Sovereign Vault'],
    content: documentContents['article-2-18'],
  },
  {
    id: 24,
    name: '2.19: UNIVESTOR Wallet Functionalities',
    group: 'part-2',
    lang: 'en',
    summary: 'Details the wallet’s role in trading DXBTOKENS and DLD-AED, its fiat-only approach, and its advanced passwordless security features.',
    keyTopics: ['Fiat-Only', 'Passwordless Security', 'Deep Security'],
    content: documentContents['article-2-19'],
  },
  {
    id: 25,
    name: '3.1: Governmental Integration',
    group: 'part-3',
    lang: 'en',
    summary: 'Outlines the deep synchronization with internal DLD modules and extensive API integrations with other UAE government entities.',
    keyTopics: ['Smart Oracles', 'API Integrations', 'Governing Council'],
    content: documentContents['article-3-1'],
  },
  {
    id: 26,
    name: '3.2: Stakeholder Integration',
    group: 'part-3',
    lang: 'en',
    summary: 'Describes how DLDCHAIN connects and governs various industry stakeholders like developers, brokers, owners, and financial institutions.',
    keyTopics: ['Data Flow', 'Developer Integration', 'Broker Management'],
    content: documentContents['article-3-2'],
  },
  {
    id: 27,
    name: '3.3: Cryptographic Security Overview',
    group: 'part-3',
    lang: 'en',
    summary: 'Presents the cryptographic foundation of DLDCHAIN, focusing on immutability, permissioned access, and data confidentiality through Hyperledger Fabric.',
    keyTopics: ['Immutability', 'Permissioned Access', 'Private Data'],
    content: documentContents['article-3-3'],
  },
  {
    id: 28,
    name: '3.4: Advanced Security Features',
    group: 'part-3',
    lang: 'en',
    summary: 'Details advanced features like the "Lost Key Solution" for inheritability, the fiat-only approach, and the zero-trust architecture.',
    keyTopics: ['Lost Key Solution', 'Inheritability', 'Zero-Trust'],
    content: documentContents['article-3-4'],
  },
  {
    id: 29,
    name: '4.1: Economic & Governance Overview',
    group: 'part-4',
    lang: 'en',
    summary: 'Provides a holistic overview of the integrated economic, legal, and governance models that ensure the protocol’s long-term sustainability.',
    keyTopics: ['Integrated Model', 'Sovereign Oversight', 'Sustainability'],
    content: documentContents['article-4-1'],
  },
  {
    id: 30,
    name: '4.2: Automation Engine Overview',
    group: 'part-4',
    lang: 'en',
    summary: 'Introduces the AI-powered Automation & Reporting Engine and how it sources real-time data from Mashroi and other integrated systems.',
    keyTopics: ['Reporting Engine', 'Data Contribution', 'Smart Oracles'],
    content: documentContents['article-4-2'],
  },
  {
    id: 31,
    name: '4.3: Market Analytics & Fraud Prevention',
    group: 'part-4',
    lang: 'en',
    summary: 'Details the engine’s capabilities for providing smart reports, live dashboards, market analytics, and AI-powered fraud prevention.',
    keyTopics: ['Smart Reports', 'Market Analytics', 'Fraud Prevention'],
    content: documentContents['article-4-3'],
  },
  {
    id: 32,
    name: '4.4: Automated Compliance (RegTech)',
    group: 'part-4',
    lang: 'en',
    summary: 'Explains how the architecture facilitates automated regulation and compliance, transforming manual processes into proactive, embedded network functions.',
    keyTopics: ['RegTech', 'Automated Regulation', 'Auditor Nodes'],
    content: documentContents['article-4-4'],
  },
  {
    id: 33,
    name: '4.5: Economic Models Overview',
    group: 'part-4',
    lang: 'en',
    summary: 'Positions DLDCHAIN as a sovereign-grade financial engine with a diversified portfolio of revenue streams to ensure long-term viability.',
    keyTopics: ['Financial Engine', 'Revenue Channels', 'Self-Sustaining'],
    content: documentContents['article-4-5'],
  },
  {
    id: 34,
    name: '4.6: Key Revenue Streams',
    group: 'part-4',
    lang: 'en',
    summary: 'Details the specific revenue channels, including token issuance fees, compliance gate revenues, visa fees, and API licensing.',
    keyTopics: ['Token Fees', 'Mashroi Revenue', 'API Licensing'],
    content: documentContents['article-4-6'],
  },
  {
    id: 35,
    name: '4.7: Strategic Alignment',
    group: 'part-4',
    lang: 'en',
    summary: 'Explains how the revenue models align with Dubai’s broader economic objectives to ensure financial self-sufficiency and reinforce global leadership.',
    keyTopics: ['Global Leadership', 'Self-Sufficiency', 'Ownership-First'],
    content: documentContents['article-4-7'],
  },
  {
    id: 36,
    name: '5.1: Global Export Framework',
    group: 'part-5',
    lang: 'en',
    summary: 'Presents the vision for exporting DLDCHAIN as a sovereign model for cities worldwide through a multi-city white-label strategy.',
    keyTopics: ['Sovereign Model', 'White-Label', 'Exchange Hub'],
    content: documentContents['article-5-1'],
  },
  {
    id: 37,
    name: '5.2: Export Challenges',
    group: 'part-5',
    lang: 'en',
    summary: 'Discusses the crucial nuances and challenges for global export, including data sovereignty, legal harmonization, and currency adoption.',
    keyTopics: ['Data Sovereignty', 'Legal Harmonization', 'Political Will'],
    content: documentContents['article-5-2'],
  },
  {
    id: 38,
    name: '5.3: Implementation Roadmap',
    group: 'part-5',
    lang: 'en',
    summary: 'Outlines the comprehensive, multi-phased roadmap for DLDCHAIN’s development, pilot, full rollout, and ecosystem expansion.',
    keyTopics: ['Phased Rollout', 'Governance', 'Secondary Market'],
    content: documentContents['article-5-3'],
  },
  {
    id: 39,
    name: '5.4: Attribution & Intent',
    group: 'part-5',
    lang: 'en',
    summary: 'A formal statement clarifying the project as a non-commercial, national contribution with all rights transferred to the Government of Dubai.',
    keyTopics: ['National Contribution', 'Sovereign Attribution', 'No Commercial Claim'],
    content: documentContents['article-5-4'],
  },
  {
    id: 40,
    name: '5.5: Institutional Submission Letter',
    group: 'part-5',
    lang: 'en',
    summary: 'The formal letter submitting the DLDCHAIN protocol to the Dubai Land Department, outlining its core models and operational philosophy.',
    keyTopics: ['Submission Letter', 'Constituent Elements', 'Operational Philosophy'],
    content: documentContents['article-5-5'],
  }
];
